name: pdfhandling
channels:
  - defaults
  - conda-forge
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2021.1.19=haa95532_1
  - cairo=1.16.0=hb19e0ff_1008
  - certifi=2020.12.5=py38haa95532_0
  - fontconfig=2.13.1=h1989441_1004
  - freetype=2.10.4=h546665d_1
  - gettext=0.19.8.1=h1a89ca6_1005
  - icu=68.1=h0e60522_0
  - intel-openmp=2020.2=254
  - jpeg=9d=h8ffe710_0
  - krb5=1.17.2=hbae68bd_0
  - libcurl=7.75.0=hf1763fc_0
  - libffi=3.3=h0e60522_2
  - libglib=2.68.0=h1e62bf3_2
  - libiconv=1.16=he774522_0
  - libpng=1.6.37=h1d00b33_2
  - libssh2=1.9.0=h680486a_6
  - libtiff=4.2.0=hc10be44_0
  - libxml2=2.9.10=hf5bbc77_3
  - lz4-c=1.9.3=h8ffe710_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38h196d8e1_0
  - mkl_fft=1.3.0=py38h46781fe_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - numpy-base=1.19.2=py38ha3acd2a_0
  - openjpeg=2.4.0=h48faf41_0
  - openssl=1.1.1k=h2bbff1b_0
  - pandas=1.2.3=py38hf11a4ad_0
  - pcre=8.44=ha925a31_0
  - pip=21.0.1=py38haa95532_0
  - pixman=0.40.0=h8ffe710_0
  - poppler=21.03.0=h9ff6ed8_0
  - poppler-data=0.4.10=0
  - python=3.8.8=hdbf39b2_4
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd3eb1b0_0
  - setuptools=52.0.0=py38haa95532_0
  - six=1.15.0=py38haa95532_0
  - sqlite=3.35.2=h2bbff1b_0
  - tabulate=0.8.9=py38haa95532_0
  - tk=8.6.10=h8ffe710_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py38_0
  - xz=5.2.5=h62dcd97_1
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.4.9=h6255e5f_0
  - pip:
    - aiohttp==3.7.4.post0
    - aiohttp-cors==0.7.0
    - appdirs==1.4.4
    - async-timeout==3.0.1
    - attrs==20.3.0
    - black==20.8b1
    - cffi==1.14.5
    - chardet==4.0.0
    - click==7.1.2
    - coloredlogs==15.0
    - cryptography==3.4.7
    - distro==1.5.0
    - et-xmlfile==1.0.1
    - humanfriendly==9.1
    - idna==3.1
    - img2pdf==0.4.0
    - lxml==4.6.3
    - multidict==5.1.0
    - mypy-extensions==0.4.3
    - numpy==1.20.2
    - ocrmypdf==11.7.3
    - openpyxl==3.0.7
    - pathspec==0.8.1
    - pdfminer-six==20200517
    - pdfplumber==0.5.27
    - pdftotext==2.1.5
    - pikepdf==2.9.2
    - pillow==8.1.2
    - pluggy==0.13.1
    - pycparser==2.20
    - pycryptodome==3.10.1
    - pypdf2==1.26.0
    - pyreadline==2.1
    - regex==2021.3.17
    - reportlab==3.5.66
    - sortedcontainers==2.3.0
    - tabula-py==2.2.0
    - toml==0.10.2
    - tqdm==4.59.0
    - typed-ast==1.4.2
    - typing-extensions==3.7.4.3
    - wand==0.6.6
    - xlrd==2.0.1
    - xlsxwriter==1.3.8
    - yarl==1.6.3
prefix: C:\Users\gunnara\Miniconda3\envs\pdfhandling
